name: Build Nitter

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: write

jobs:
  build:
    if: (github.event_name != 'schedule' || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Nitter code
      uses: actions/checkout@v3
      with:
        repository: zedeus/nitter
        ref: master

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1.4.7

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libsass-dev

    - name: Build Nitter for AMD 64
      run: |
        nimble build -y -d:release
        nimble scss
        nimble md
        cp nitter.example.conf nitter.conf
        tar -czvf nitter-amd64.tar.gz nitter public nitter.conf
        rm nitter

    - name: Build Nitter for ARM 64
      run: |
        nimble build -y -d:release --cpu:arm64
        tar -czvf nitter-arm64.tar.gz nitter public nitter.conf

    - name: Create Release Name
      run: echo "RELEASE_NAME=$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Create GitHub Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.RELEASE_NAME }}
        files: |
          nitter-amd64.tar.gz
          nitter-arm64.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ env.RELEASE_NAME }}